import { Building2, Search } from "lucide-react";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Brand } from "@/components/brand";
import { EmptyState } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { businessSlug } from "@/lib/business-slug";
import { getBusinesses } from "@/services/api";
import type { Business } from "@/types";

export function BusinessSearchPage() { const [businesses, setBusinesses] = useState<Business[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { void getBusinesses().then(setBusinesses).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load businesses.")).finally(() => setLoading(false)); }, []); const visible = businesses.filter((business) => `${business.name} ${business.businessType} ${business.description ?? ""}`.toLowerCase().includes(query.toLowerCase())); return <main className="min-h-screen"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><Link to="/"><Brand /></Link><Button variant="ghost" asChild><Link to="/owner/onboarding">List your business</Link></Button></header><section className="mx-auto max-w-7xl px-5 py-12 md:px-8"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><p className="text-sm text-accent">Find local businesses</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Talk to a business, naturally.</h1><p className="mt-3 max-w-2xl text-muted">Choose a business and chat directly with its AI receptionist.</p></motion.div><label className="mt-8 flex max-w-2xl items-center gap-3 rounded-xl border border-border bg-surface px-4"><Search className="h-5 w-5 text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-14 flex-1 bg-transparent text-sm outline-none placeholder:text-muted" placeholder="Search by business name or type" /></label><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{loading ? Array.from({ length: 6 }, (_, index) => <div key={index} className="h-56 animate-pulse rounded-xl border border-border bg-surface" />) : error ? <div className="col-span-full rounded-xl border border-[#7f1d1d] bg-[#450a0a]/40 p-5 text-sm text-[#fca5a5]">{error}</div> : visible.map((business, index) => <motion.article key={business.id ?? business._id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} className="flex flex-col rounded-xl border border-border bg-surface p-5"><Building2 className="h-6 w-6 text-accent" /><p className="mt-6 text-xs uppercase tracking-wider text-accent">{business.businessType}</p><h2 className="mt-2 text-lg font-semibold">{business.name}</h2><p className="mt-2 flex-1 text-sm leading-6 text-muted">{business.description ?? `${business.businessType} available through BizzAI.`}</p><div className="mt-6"><Button asChild><Link to={`/business/${businessSlug(business)}`}>Open business</Link></Button></div></motion.article>)}</div>{!loading && !error && visible.length === 0 && <EmptyState icon={Building2} title="No matching businesses" description="Try a different search or check back later." />}</section></main>; }
