import { Plus, Search, SlidersHorizontal, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { DataDetails, hasDisplayValue } from "@/components/data-details";
import { Dialog, EmptyState, LoadingCards, PageHeader } from "@/components/dashboard-ui";
import { useOwnerBusiness } from "@/hooks/use-owner-business";
import { createOperation, getOperations } from "@/services/api";
import type { Operation } from "@/types";
import { useToast } from "@/contexts/toast-context";

export function OwnerOperationsPage() {
  const { show } = useToast();
  const { businessId, loading: businessLoading } = useOwnerBusiness();
  const [operations, setOperations] = useState<Operation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Operation | null>(null); const [creating, setCreating] = useState(false);
  const [search, setSearch] = useState(""); const [entityType, setEntityType] = useState("all"); const [status, setStatus] = useState("all"); const [order, setOrder] = useState("newest");
  const load = async () => { if (!businessId) { setLoading(false); return; } setLoading(true); try { const items = await getOperations(); setOperations(items.filter((item) => item.businessId === businessId)); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to load operations."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [businessId]);
  const filtered = useMemo(() => operations.filter((item) => (entityType === "all" || item.entityType === entityType) && (status === "all" || item.status === status) && JSON.stringify(item).toLowerCase().includes(search.toLowerCase())).sort((a, b) => order === "newest" ? +new Date(b.createdAt) - +new Date(a.createdAt) : +new Date(a.createdAt) - +new Date(b.createdAt)), [operations, entityType, status, search, order]);
  const types = [...new Set(operations.map((item) => item.entityType))]; const statuses = [...new Set(operations.map((item) => item.status))];
  if (businessLoading || loading) return <LoadingCards />;
  return <><PageHeader title="Operations" description="A unified view of records across every business capability." action={<Button onClick={() => setCreating(true)}><Plus className="mr-2 h-4 w-4" />Create Operation</Button>} /><div className="mt-8 rounded-xl border border-border bg-surface"><div className="flex flex-col gap-3 border-b border-border p-4 lg:flex-row"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-lg border border-border bg-[#0F172A] px-3"><Search className="h-4 w-4 text-muted" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted" placeholder="Search operations" /></label><div className="grid grid-cols-2 gap-3 sm:flex"><Select value={entityType} onChange={setEntityType} options={["all", ...types]} label="Type" /><Select value={status} onChange={setStatus} options={["all", ...statuses]} label="Status" /><Select value={order} onChange={setOrder} options={["newest", "oldest"]} label="Order" includeAll={false} /></div></div>{error ? <div className="p-6 text-sm text-[#fca5a5]">{error}</div> : filtered.length ? <OperationTable operations={filtered} onSelect={setSelected} /> : <EmptyState icon={Wrench} title="No operations yet" description="Create a raw operation to demonstrate the generic operations model." action={<Button onClick={() => setCreating(true)}>Create Operation</Button>} />}</div>{selected && <OperationDetails operation={selected} onClose={() => setSelected(null)} />}{creating && businessId && <CreateOperationDialog businessId={businessId} onClose={() => setCreating(false)} onCreated={(operation) => { setOperations((items) => [operation, ...items]); show("success", "Operation created."); setCreating(false); }} />}</>;
}

function OperationTable({ operations, onSelect }: { operations: Operation[]; onSelect: (operation: Operation) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted"><tr><th className="px-5 py-4">Type</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Created</th><th className="px-5 py-4">Last updated</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{operations.map((operation) => <motion.tr initial={{ opacity: 0 }} animate={{ opacity: 1 }} key={operation.id ?? operation._id} className="border-t border-border text-muted hover:bg-slate-800/40"><td className="px-5 py-4 font-medium capitalize text-foreground">{operation.entityType}</td><td className="px-5 py-4"><span className="rounded-full border border-border px-2.5 py-1 text-xs">{operation.status}</span></td><td className="px-5 py-4">{customerName(operation.data)}</td><td className="px-5 py-4">{date(operation.createdAt)}</td><td className="px-5 py-4">{date(operation.updatedAt)}</td><td className="px-5 py-4 text-right"><Button variant="ghost" onClick={() => onSelect(operation)}>View</Button></td></motion.tr>)}</tbody></table></div>; }
function OperationDetails({ operation, onClose }: { operation: Operation; onClose: () => void }) { return <Dialog title="Operation details" onClose={onClose}><dl className="space-y-5"><Value label="Entity type" value={operation.entityType} /><Value label="Status" value={operation.status} /><JsonValue label="Data" value={operation.data} /><JsonValue label="Metadata" value={operation.metadata} /><Value label="Created" value={date(operation.createdAt)} /><Value label="Last updated" value={date(operation.updatedAt)} /></dl></Dialog>; }
function CreateOperationDialog({ businessId, onClose, onCreated }: { businessId: string; onClose: () => void; onCreated: (operation: Operation) => void }) { const [entityType, setEntityType] = useState(""); const [status, setStatus] = useState("pending"); const [data, setData] = useState("{\n  \n}"); const [metadata, setMetadata] = useState("{\n  \n}"); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const submit = async () => { try { setError(null); if (!entityType.trim() || !status.trim()) throw new Error("Type and status are required."); const parsedData = parseObject(data, "Data"); const parsedMetadata = parseObject(metadata, "Metadata"); setSaving(true); onCreated(await createOperation({ businessId, entityType: entityType.trim(), status: status.trim(), data: parsedData, metadata: parsedMetadata })); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to create operation."); } finally { setSaving(false); } }; return <Dialog title="Create Operation" onClose={onClose}><p className="text-sm text-muted">Create generic raw operation data for a demo. The backend validates the request.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Entity type" value={entityType} onChange={setEntityType} placeholder="appointment, order, reservation" /><Input label="Status" value={status} onChange={setStatus} placeholder="pending" /></div><JsonInput label="Data" value={data} onChange={setData} /><JsonInput label="Metadata" value={metadata} onChange={setMetadata} />{error && <p className="mt-4 text-sm text-[#fca5a5]">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? "Creating…" : "Create Operation"}</Button></div></Dialog>; }
function Select({ value, onChange, options, label, includeAll = true }: { value: string; onChange: (value: string) => void; options: string[]; label: string; includeAll?: boolean }) { return <select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-lg border border-border bg-[#0F172A] px-3 text-sm text-muted outline-none">{includeAll && <option value="all">All {label.toLowerCase()}s</option>}{options.filter((option) => option !== "all").map((option) => <option key={option} value={option}>{option}</option>)}</select>; }
function Input({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="text-sm text-muted">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 h-10 w-full rounded-lg border border-border bg-[#0F172A] px-3 text-sm text-foreground outline-none focus:border-primary" /></label>; }
function JsonInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mt-4 block text-sm text-muted">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-28 w-full rounded-lg border border-border bg-[#0F172A] p-3 font-mono text-xs text-foreground outline-none focus:border-primary" /></label>; }
function Value({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wider text-muted">{label}</dt><dd className="mt-2 text-sm capitalize">{value}</dd></div>; }
function JsonValue({ label, value }: { label: string; value: Record<string, unknown> }) { if (!hasDisplayValue(value)) return null; return <div><dt className="text-xs font-medium uppercase tracking-wider text-muted">{label}</dt><dd className="mt-2"><DataDetails value={value} /></dd></div>; }
function parseObject(value: string, label: string): Record<string, unknown> { try { const parsed: unknown = JSON.parse(value); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); return parsed as Record<string, unknown>; } catch { throw new Error(`${label} must contain a valid JSON object.`); } }
function customerName(data: Record<string, unknown>) { const customer = data.customer; if (typeof customer === "string") return customer; const name = data.customerName; return typeof name === "string" ? name : "—"; }
function date(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
