import { Building2, Pencil, Save, X } from "lucide-react";
import { useState } from "react";
import { DataDetails } from "@/components/data-details";
import { EmptyState, LoadingCards, PageHeader, Panel, Tags } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { useToast } from "@/contexts/toast-context";
import { useOwnerBusiness } from "@/hooks/use-owner-business";
import { updateBusiness } from "@/services/api";
import type { Business } from "@/types";

export function OwnerProfilePage() {
  const { business, businessId, loading, error, reload } = useOwnerBusiness();
  const [editing, setEditing] = useState(false);
  if (loading) return <LoadingCards />;
  if (!business || !businessId) return <EmptyState icon={Building2} title="Business unavailable" description={error ?? "Complete onboarding to view your business profile."} />;
  return <><PageHeader title="Business profile" description="Manage the information BizzAI uses to represent your business." action={<Button onClick={() => setEditing((value) => !value)} variant={editing ? "outline" : "default"}>{editing ? <><X className="mr-2 h-4 w-4" />Cancel</> : <><Pencil className="mr-2 h-4 w-4" />Edit business</>}</Button>} />{editing ? <BusinessEditor business={business} businessId={businessId} onSaved={async () => { setEditing(false); await reload(); }} /> : <BusinessSummary business={business} />}</>;
}

function BusinessSummary({ business }: { business: Business }) {
  return <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Core details"><div className="space-y-5 text-sm"><Field label="Business name" value={business.name} /><Field label="Business type" value={business.businessType} /><Field label="Description" value={business.description ?? "Not provided"} /><Field label="Address" value={business.address ?? "Not provided"} /><Field label="Phone" value={business.phone ?? "Not provided"} /></div></Panel><Panel title="Capabilities and rules"><p className="text-xs font-medium uppercase tracking-wider text-muted">Capabilities</p><div className="mt-3"><Tags values={business.capabilities} /></div><p className="mt-7 text-xs font-medium uppercase tracking-wider text-muted">Rules</p><ul className="mt-3 space-y-2 text-sm text-muted">{business.rules.length ? business.rules.map((rule) => <li key={rule}>• {rule}</li>) : <li>No rules configured</li>}</ul></Panel>{Object.keys(business.configuration).length > 0 && <Panel title="Configuration" className="lg:col-span-2"><DataDetails value={business.configuration} /></Panel>}</div>;
}

function BusinessEditor({ business, businessId, onSaved }: { business: Business; businessId: string; onSaved: () => Promise<void> }) {
  const { show } = useToast();
  const [name, setName] = useState(business.name); const [businessType, setBusinessType] = useState(business.businessType); const [description, setDescription] = useState(business.description ?? ""); const [address, setAddress] = useState(business.address ?? ""); const [phone, setPhone] = useState(business.phone ?? "");
  const [capabilities, setCapabilities] = useState(business.capabilities.join(", ")); const [rules, setRules] = useState(business.rules.join("\n")); const [services, setServices] = useState(stringList(business.configuration.services).join(", ")); const [slotDuration, setSlotDuration] = useState(typeof business.configuration.slotDuration === "number" ? String(business.configuration.slotDuration) : "");
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const save = async () => { try { setSaving(true); setError(null); const duration = slotDuration.trim() ? Number(slotDuration) : undefined; if (duration !== undefined && (!Number.isFinite(duration) || duration <= 0)) throw new Error("Slot duration must be a positive number."); const configuration = { ...business.configuration, services: splitList(services), ...(duration === undefined ? {} : { slotDuration: duration }) }; await updateBusiness(businessId, { name: name.trim(), businessType: businessType.trim(), description: description.trim(), address: address.trim(), phone: phone.trim(), capabilities: splitList(capabilities), rules: splitLines(rules), configuration }); show("success", "Business profile updated."); await onSaved(); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to update business."); } finally { setSaving(false); } };
  return <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Business details"><div className="grid gap-4"><Input label="Business name" value={name} onChange={setName} /><Input label="Business type" value={businessType} onChange={setBusinessType} /><TextArea label="Description" value={description} onChange={setDescription} /><Input label="Address" value={address} onChange={setAddress} /><Input label="Phone" value={phone} onChange={setPhone} /></div></Panel><Panel title="Receptionist settings"><div className="grid gap-4"><Input label="Capabilities" value={capabilities} onChange={setCapabilities} hint="Comma-separated, for example: appointments, faq" /><Input label="Services" value={services} onChange={setServices} hint="Comma-separated services offered by your business" /><Input label="Slot duration (minutes)" value={slotDuration} onChange={setSlotDuration} hint="Used for appointment availability" /><TextArea label="Business rules" value={rules} onChange={setRules} hint="One rule per line" /></div></Panel><div className="lg:col-span-2 flex flex-col-reverse gap-3 border-t border-border pt-6 sm:flex-row sm:justify-end"><p className="mr-auto text-sm text-muted">Changes apply to new receptionist conversations immediately.</p>{error && <p className="text-sm text-[#fca5a5]">{error}</p>}<Button onClick={() => void save()} disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Saving…" : "Save changes"}</Button></div></div>;
}

function Input({ label, value, onChange, hint }: { label: string; value: string; onChange: (value: string) => void; hint?: string }) { return <label className="text-sm font-medium">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-border bg-[#0F172A] px-3 text-sm font-normal outline-none focus:border-primary" />{hint && <span className="mt-1 block text-xs font-normal text-muted">{hint}</span>}</label>; }
function TextArea({ label, value, onChange, hint }: { label: string; value: string; onChange: (value: string) => void; hint?: string }) { return <label className="text-sm font-medium">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-24 w-full resize-y rounded-lg border border-border bg-[#0F172A] p-3 text-sm font-normal outline-none focus:border-primary" />{hint && <span className="mt-1 block text-xs font-normal text-muted">{hint}</span>}</label>; }
function Field({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium uppercase tracking-wider text-muted">{label}</p><p className="mt-1.5 text-foreground">{value}</p></div>; }
function stringList(value: unknown): string[] { return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : []; }
function splitList(value: string): string[] { return value.split(",").map((entry) => entry.trim()).filter(Boolean); }
function splitLines(value: string): string[] { return value.split("\n").map((entry) => entry.trim()).filter(Boolean); }
