import type { Business } from "../models/business.model.js";
import type { OperationRequest, OperationResult } from "../types/operation.js";
import { BaseEngine } from "./base-engine.js";
import { businessId, configHours, configNumber, isValidCustomerName, minutes, overlaps, text, timeFromMinutes } from "./engine-utils.js";

export class AppointmentEngine extends BaseEngine {
  readonly capability = "appointments";
  async query(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; if (request.action === "availability") return this.availability(request, business); return this.success("Appointments retrieved.", null, { appointments: (await this.recordsFor(business)).map((record) => this.serialize(record)) }); }
  async mutate(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; if (request.action === "create") return this.create(request, business); const id = text(request.payload, "operationId"); if (!id) return this.failure("operationId is required."); const existing = await this.records.findById(id); if (String(existing.businessId) !== businessId(business) || existing.entityType !== "appointment") return this.failure("Appointment was not found."); if (request.action === "cancel" || request.action === "delete") return this.success("Appointment cancelled.", this.serialize(await this.records.update(id, { status: "cancelled" }))); if (request.action === "update") { if (!this.active(existing)) return this.failure("A cancelled or completed appointment cannot be updated."); return this.success("Appointment updated.", this.serialize(await this.records.update(id, { status: text(request.payload, "status") ?? existing.status, data: { ...existing.data, ...request.payload } }))); } return this.failure("Unsupported appointment action."); }
  async suggest(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; return this.availability({ ...request, action: "availability" }, business); }
  private async create(request: OperationRequest, business: Business): Promise<OperationResult> { const date = text(request.payload, "date"); const startTime = text(request.payload, "startTime"); const customer = text(request.payload, "customer"); if (!date || !startTime || !customer) return this.failure("date, startTime, and customer are required."); if (!isValidCustomerName(customer)) return this.failure("Please provide your full name to complete the booking."); const duration = configNumber(business, "slotDuration", 30); const start = minutes(startTime); const end = start === null ? null : start + duration; const hours = configHours(business, date); if (start === null || end === null) return this.failure("startTime must use HH:MM format."); if (!hours) return this.failure("Working hours are not configured for the requested date."); const open = minutes(hours.start); const close = minutes(hours.end); if (open === null || close === null || start < open || end > close) return this.failure("The requested time is outside business hours."); const conflicts = (await this.recordsFor(business)).some((record) => { const data = record.data; return this.active(record) && data.date === date && typeof data.startTime === "string" && typeof data.endTime === "string" && overlaps(start, end, minutes(data.startTime) ?? 0, minutes(data.endTime) ?? 0); }); if (conflicts) return this.failure("The requested appointment slot is already occupied."); const record = await this.records.create({ businessId: businessId(business), entityType: "appointment", status: "confirmed", data: { ...request.payload, date, startTime, endTime: timeFromMinutes(end), customer }, metadata: {} }); return this.success("Appointment confirmed.", this.serialize(record), { endTime: timeFromMinutes(end) }); }
  private async availability(request: OperationRequest, business: Business): Promise<OperationResult> { const date = text(request.payload, "date"); if (!date) return this.failure("date is required to find availability."); const hours = configHours(business, date); if (!hours) return this.failure("Working hours are not configured for the requested date."); const duration = configNumber(business, "slotDuration", 30); const open = minutes(hours.start); const close = minutes(hours.end); if (open === null || close === null) return this.failure("Working hours use an invalid time format."); const appointments = await this.recordsFor(business); const slots: string[] = []; for (let start = open; start + duration <= close; start += duration) { const end = start + duration; const taken = appointments.some((record) => record.data.date === date && this.active(record) && typeof record.data.startTime === "string" && typeof record.data.endTime === "string" && overlaps(start, end, minutes(record.data.startTime) ?? 0, minutes(record.data.endTime) ?? 0)); if (!taken) slots.push(timeFromMinutes(start)); } return this.success(slots.length ? "Available appointment slots found." : "No appointment slots are available.", null, { date, duration, slots }); }
}
