import type { Business } from "../models/business.model.js";
import type { OperationRequest, OperationResult } from "../types/operation.js";
import { BaseEngine } from "./base-engine.js";
import { businessId, configNumber, text } from "./engine-utils.js";

export class OrderEngine extends BaseEngine {
  readonly capability = "orders";
  async query(_request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; return this.success("Orders retrieved.", null, { orders: (await this.recordsFor(business)).map((record) => this.serialize(record)) }); }
  async mutate(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; if (request.action === "create") { const customer = text(request.payload, "customer"); if (!customer) return this.failure("customer is required to create an order."); const estimate = configNumber(business, "estimatedCompletionMinutes", configNumber(business, "prepTime", 30)); const record = await this.records.create({ businessId: businessId(business), entityType: "order", status: "pending", data: { ...request.payload, customer }, metadata: { estimatedCompletionMinutes: estimate } }); return this.success("Order created.", this.serialize(record), { estimatedCompletionMinutes: estimate }); } const id = text(request.payload, "operationId"); if (!id) return this.failure("operationId is required."); const order = await this.records.findById(id); if (String(order.businessId) !== businessId(business) || order.entityType !== "order") return this.failure("Order was not found."); if (["completed", "delivered", "cancelled"].includes(order.status.toLowerCase()) && request.action !== "update") return this.failure("This order can no longer be changed."); if (request.action === "cancel" || request.action === "delete") return this.success("Order cancelled.", this.serialize(await this.records.update(id, { status: "cancelled" }))); if (request.action === "update") return this.success("Order updated.", this.serialize(await this.records.update(id, { status: text(request.payload, "status") ?? order.status, data: { ...order.data, ...request.payload } }))); return this.failure("Unsupported order action."); }
  async suggest(_request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; const minutes = configNumber(business, "estimatedCompletionMinutes", configNumber(business, "prepTime", 30)); return this.success("Estimated order completion calculated.", null, { estimatedCompletionMinutes: minutes }); }
}
