import type { Business } from "../models/business.model.js";
import type { OperationRequest, OperationResult } from "../types/operation.js";
import { BaseEngine } from "./base-engine.js";
import { businessId, configNumber, text } from "./engine-utils.js";

export class QueueEngine extends BaseEngine {
  readonly capability = "queue";
  async query(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; const queue = (await this.recordsFor(business)).filter((record) => this.active(record)); const id = text(request.payload, "operationId"); if (id) { const position = queue.findIndex((record) => String((record as { _id?: unknown })._id) === id) + 1; return position ? this.success("Queue position retrieved.", null, { position, estimatedWaitMinutes: (position - 1) * configNumber(business, "averageServiceMinutes", 15) }) : this.failure("Queue entry was not found."); } return this.success("Queue retrieved.", null, { entries: queue.map((record) => this.serialize(record)), count: queue.length }); }
  async mutate(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; if (request.action === "create" || request.action === "add") { const customer = text(request.payload, "customer"); if (!customer) return this.failure("customer is required to join the queue."); const queue = (await this.recordsFor(business)).filter((record) => this.active(record)); const record = await this.records.create({ businessId: businessId(business), entityType: "queue", status: "waiting", data: { ...request.payload, customer }, metadata: { position: queue.length + 1 } }); return this.success("Customer added to the queue.", this.serialize(record), { position: queue.length + 1, estimatedWaitMinutes: queue.length * configNumber(business, "averageServiceMinutes", 15) }); } const id = text(request.payload, "operationId"); if (!id) return this.failure("operationId is required."); const record = await this.records.findById(id); if (String(record.businessId) !== businessId(business) || record.entityType !== "queue") return this.failure("Queue entry was not found."); if (request.action === "remove" || request.action === "cancel") return this.success("Customer removed from the queue.", this.serialize(await this.records.update(id, { status: "cancelled" }))); if (request.action === "update") return this.success("Queue entry updated.", this.serialize(await this.records.update(id, { status: text(request.payload, "status") ?? record.status, data: { ...record.data, ...request.payload } }))); return this.failure("Unsupported queue action."); }
  async suggest(_request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; const count = (await this.recordsFor(business)).filter((record) => this.active(record)).length; const avg = configNumber(business, "averageServiceMinutes", 15); return this.success("Queue wait estimate calculated.", null, { queueLength: count, estimatedWaitMinutes: count * avg }); }
}
