import type { Business } from "../models/business.model.js";
import type { OperationRequest, OperationResult } from "../types/operation.js";
import { BaseEngine } from "./base-engine.js";
import { businessId, minutes, overlaps, text, timeFromMinutes } from "./engine-utils.js";

export class ReservationEngine extends BaseEngine {
  readonly capability = "reservations";
  async query(_request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; return this.success("Reservations retrieved.", null, { reservations: (await this.recordsFor(business)).map((record) => this.serialize(record)) }); }
  async mutate(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; if (request.action === "create") { const resource = text(request.payload, "resource"); const date = text(request.payload, "date"); const startTime = text(request.payload, "startTime"); const duration = typeof request.payload.duration === "number" ? request.payload.duration : null; const customer = text(request.payload, "customer"); if (!resource || !date || !startTime || !duration || !customer) return this.failure("resource, date, startTime, duration, and customer are required."); const start = minutes(startTime); if (start === null || duration <= 0) return this.failure("Reservation time or duration is invalid."); const end = start + duration * 60; const conflict = (await this.recordsFor(business)).some((record) => this.active(record) && record.data.resource === resource && record.data.date === date && typeof record.data.startTime === "string" && typeof record.data.endTime === "string" && overlaps(start, end, minutes(record.data.startTime) ?? 0, minutes(record.data.endTime) ?? 0)); if (conflict) return this.failure("The requested resource is already reserved for that time."); const record = await this.records.create({ businessId: businessId(business), entityType: "reservation", status: "confirmed", data: { ...request.payload, resource, date, startTime, endTime: timeFromMinutes(end), customer }, metadata: {} }); return this.success("Reservation confirmed.", this.serialize(record)); } const id = text(request.payload, "operationId"); if (!id) return this.failure("operationId is required."); const record = await this.records.findById(id); if (String(record.businessId) !== businessId(business) || record.entityType !== "reservation") return this.failure("Reservation was not found."); if (request.action === "cancel") return this.success("Reservation cancelled.", this.serialize(await this.records.update(id, { status: "cancelled" }))); if (request.action === "update") return this.success("Reservation updated.", this.serialize(await this.records.update(id, { status: text(request.payload, "status") ?? record.status, data: { ...record.data, ...request.payload } }))); return this.failure("Unsupported reservation action."); }
  async suggest(request: OperationRequest, business: Business): Promise<OperationResult> { const blocked = this.supported(business); if (blocked) return blocked; const resource = text(request.payload, "resource"); if (!resource) return this.failure("resource is required for a reservation suggestion."); const active = (await this.recordsFor(business)).filter((record) => this.active(record) && record.data.resource === resource); return this.success("Reservation suggestion calculated.", null, { resource, activeReservations: active.length, suggestedDurationHours: 1 }); }
}
