import { Bot, Building2, LayoutDashboard, LogOut, Menu, MessageSquare, Settings, Wrench } from "lucide-react";
import { useState } from "react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { useRole } from "@/contexts/role-context";
import { cn } from "@/lib/utils";

const ownerItems = [{ to: "/owner/dashboard", label: "Dashboard", icon: LayoutDashboard }, { to: "/owner/operations", label: "Operations", icon: Wrench }, { to: "/owner/profile", label: "Business Profile", icon: Building2 }, { to: "/owner/ai-configuration", label: "AI Configuration", icon: Bot }, { to: "/owner/settings", label: "Settings", icon: Settings }];
const customerItems = [{ to: "/customer", label: "Find a business", icon: MessageSquare }];
export function AppLayout() { const { role, clearRole } = useRole(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const items = role === "owner" ? ownerItems : customerItems; const leave = () => { clearRole(); navigate("/"); }; const sidebar = <aside className="flex h-full w-72 flex-col border-r border-border bg-[#111c31] p-5"><Link to={role === "owner" ? "/owner/dashboard" : "/customer"} onClick={() => setOpen(false)}><Brand /></Link><p className="mt-8 px-3 text-xs font-semibold uppercase tracking-[0.16em] text-muted">Workspace</p><nav className="mt-3 flex flex-1 flex-col gap-1.5">{items.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => cn("flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-medium transition-colors", isActive ? "bg-primary text-white" : "text-muted hover:bg-slate-800 hover:text-foreground")}><Icon className="h-4 w-4" />{label}</NavLink>)}</nav><Button variant="ghost" className="mt-8 w-full justify-start gap-3 border border-border" onClick={leave}><LogOut className="h-4 w-4" />Switch role</Button></aside>; return <div className="min-h-screen md:flex"><div className="hidden md:block">{sidebar}</div>{open && <div className="fixed inset-0 z-40 bg-slate-950/70 md:hidden" onClick={() => setOpen(false)}><div className="h-full" onClick={(event) => event.stopPropagation()}>{sidebar}</div></div>}<main className="min-w-0 flex-1"><header className="flex h-[72px] items-center justify-between border-b border-border bg-[#0F172A]/90 px-5 backdrop-blur-sm md:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu className="h-5 w-5" /></Button><p className="text-sm text-muted">{role === "owner" ? "Business workspace" : "Customer portal"}</p></div><span className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs font-medium capitalize text-muted">{role}</span></header><div className="mx-auto max-w-7xl p-5 md:p-8"><Outlet /></div></main></div>; }
