import type { LucideIcon } from "lucide-react";
import { X } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="text-sm text-accent">{eyebrow}</p>}<h1 className="mt-1 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted">{description}</p></div>{action}</div>; }
export function MetricCard({ label, value, icon: Icon }: { label: string; value: string | number; icon: LucideIcon }) { return <motion.article initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-border bg-surface p-5"><Icon className="h-5 w-5 text-accent" /><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-muted">{label}</p></motion.article>; }
export function Tags({ values }: { values: string[] }) { return <div className="flex flex-wrap gap-2">{values.length ? values.map((value) => <span key={value} className="rounded-full border border-border bg-[#0F172A] px-2.5 py-1 text-xs text-accent">{value}</span>) : <span className="text-sm text-muted">None configured</span>}</div>; }
export function LoadingCards() { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-36 animate-pulse rounded-xl border border-border bg-surface" />)}</div>; }
export function EmptyState({ icon: Icon, title, description, action }: { icon: LucideIcon; title: string; description: string; action?: React.ReactNode }) { return <div className="rounded-xl border border-dashed border-border bg-surface/50 px-6 py-16 text-center"><Icon className="mx-auto mb-4 h-8 w-8 text-accent" /><h2 className="text-lg font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted">{description}</p>{action && <div className="mt-6">{action}</div>}</div>; }
export function Panel({ title, children, className }: { title: string; children: React.ReactNode; className?: string }) { return <section className={cn("rounded-xl border border-border bg-surface p-5 md:p-6", className)}><h2 className="text-base font-semibold">{title}</h2><div className="mt-5">{children}</div></section>; }
export function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/75 p-4" role="dialog" aria-modal="true"><motion.div initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl border border-border bg-surface p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close"><X className="h-4 w-4" /></Button></div><div className="mt-5">{children}</div></motion.div></div>; }
